# Introduction
Modifying the Notebook that Idir did so I obly take the portrait painting

# Libraries

In [1]:
import pandas as pd
import os
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time

In [2]:
data_file = "../../data/art_catalog.xlsx"
df = pd.read_excel(data_file)
df.head(5)

,AUTHOR,BORN-DIED,TITLE,DATE,TECHNIQUE,LOCATION,URL,FORM,TYPE,SCHOOL,TIMEFRAME
0,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Venus and Adonis,1574-88,"Oil on canvas, 68 x 95 cm","Fogg Art Museum, Harvard University, Cambridge",https://www.wga.hu/html/a/aachen/adonis.html,painting,mythological,German,1601-1650
1,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Allegory,1598,"Oil on copper, 56 x 47 cm","Alte Pinakothek, Munich",https://www.wga.hu/html/a/aachen/allegory.html,painting,mythological,German,1601-1650
2,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Allegory of Peace, Art and Abundance",1602,"Oil on canvas, 197 x 142 cm","The Hermitage, St. Petersburg",https://www.wga.hu/html/a/aachen/allegorz.html,painting,mythological,German,1601-1650
3,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Jupiter, Antiope and Cupid",1595-98,"Oil on copper, 31 x 21 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/antiope.html,painting,mythological,German,1601-1650
4,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Pallas Athena, Venus and Juno",1593,"Oil on canvas, 54 x 67 cm","Museum of Fine Arts, Boston",https://www.wga.hu/html/a/aachen/athena.html,painting,mythological,German,1601-1650

Selectionne uniquement les "FORM == painting""

In [4]:
df_paint = df[(df["FORM"] == "painting") & (df["TYPE"] == "portrait")]
df_paint.head(5)

,AUTHOR,BORN-DIED,TITLE,DATE,TECHNIQUE,LOCATION,URL,FORM,TYPE,SCHOOL,TIMEFRAME
12,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Gaspar Rem,1574-75,"Oil on canvas, 49 x 42 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/portrai1.html,painting,portrait,German,1601-1650
13,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Portrait of Painter Josef Heintz,1585,"Oil on canvas, 57 x 44 cm","Národní Galerie, Prague",https://www.wga.hu/html/a/aachen/portrai2.html,painting,portrait,German,1601-1650
14,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Anna of Tyrol,1604,"Oil on canvas, 58 x 48 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/portrai3.html,painting,portrait,German,1601-1650
16,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Portrait of Emperor Rudolf II,1606-08,"Oil on canvas, 60 x 48 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/rudolf2.html,painting,portrait,German,1601-1650
17,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Two Laughing Men (Self-Portrait),before 1574,"Oil on panel, 48 x 39 cm","Archdiocesan Museum, Kromeriz",https://www.wga.hu/html/a/aachen/selfpor1.html,painting,portrait,German,1601-1650

In [5]:
df_paint.shape

(4810, 11)

In [6]:
urls = list(df_paint["URL"])

urls[:5]

['https://www.wga.hu/html/a/aachen/portrai1.html',
 'https://www.wga.hu/html/a/aachen/portrai2.html',
 'https://www.wga.hu/html/a/aachen/portrai3.html',
 'https://www.wga.hu/html/a/aachen/rudolf2.html',
 'https://www.wga.hu/html/a/aachen/selfpor1.html']

In [7]:

output_dir = "../data/paint_portrait"
os.makedirs(output_dir, exist_ok=True) 

def download_wga_image(page_url, output_dir, sleep_time=1.5):
    img_path = page_url.replace("/html/", "/detail/")
    img_url = img_path.replace(".html", ".jpg")


    filename = os.path.join(output_dir, os.path.basename(img_url))


    if os.path.exists(filename):
        print(f"L'image existe déjà : {filename}, téléchargement ignoré.")
        return


    response = requests.get(img_url)
    if response.status_code == 200:
        with open(filename, "wb") as f:
            f.write(response.content)
        print(f"Image téléchargée : {filename}")
        time.sleep(sleep_time)  
    else:
        print("Impossible de télécharger l'image :", response.status_code, img_url)

In [8]:
for url in urls:
    download_wga_image(url.strip(), output_dir)

Image téléchargée : ../data/paint_portrait/portrai1.jpg
Image téléchargée : ../data/paint_portrait/portrai2.jpg
Image téléchargée : ../data/paint_portrait/portrai3.jpg
Image téléchargée : ../data/paint_portrait/rudolf2.jpg
Image téléchargée : ../data/paint_portrait/selfpor1.jpg
Image téléchargée : ../data/paint_portrait/selfport.jpg
L'image existe déjà : ../data/paint_portrait/portrai1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrai2.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/abbati4.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/brothers.jpg
Image téléchargée : ../data/paint_portrait/v_josefa.jpg
Image téléchargée : ../data/paint_portrait/portrait.jpg
Image téléchargée : ../data/paint_portrait/portra1.jpg
L'image existe déjà : ../data/paint_portrait/portrai2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrai3.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/portrai4.jpg
Image téléchargée : ../data/paint_portrait/portrai5.jpg
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/12portra.jpg
Image téléchargée : ../data/paint_portrait/alchitro.jpg
Image téléchargée : ../data/paint_portrait/columbus.jpg
Image téléchargée : ../data/paint_portrait/fugger.jpg
Image téléchargée : ../data/paint_portrait/goldsmit.jpg
Image téléchargée : ../data/paint_portrait/munster.jpg
Image téléchargée : ../data/paint_portrait/schwarz.jpg
Image téléchargée : ../data/paint_portrait/seiler.jpg
Image téléchargée : ../data/paint_portrait/youngman.jpg
Image téléchargée : ../data/paint_portrait/youngwom.jpg
Image téléchargée : ../data/paint_portrait/arthaber.jpg
Image téléchargée : ../data/paint_portrait/franz_1.jpg
Image téléchargée : ../data/paint_portrait/girl.jpg
Image téléchargée : ../data/paint_portrait/girlport.jpg
Image téléchargée : ../data/paint_portrait/girlyel.jpg
Image téléchargée : ../data/paint_portrait/girlyell.jpg
Image téléchargée : ../data/paint_portrait/nako.jpg
Image téléchargée : ../data/paint_portrait/princess.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/szecheny.jpg
Image téléchargée : ../data/paint_portrait/portgent.jpg
Image téléchargée : ../data/paint_portrait/gentlema.jpg
Image téléchargée : ../data/paint_portrait/portlady.jpg
Image téléchargée : ../data/paint_portrait/mother.jpg
Image téléchargée : ../data/paint_portrait/rossini.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/1eve.jpg
Image téléchargée : ../data/paint_portrait/1pippo.jpg
Image téléchargée : ../data/paint_portrait/2acciaol.jpg
Image téléchargée : ../data/paint_portrait/3uberti.jpg
Image téléchargée : ../data/paint_portrait/4esther.jpg
Image téléchargée : ../data/paint_portrait/5cumean.jpg
Image téléchargée : ../data/paint_portrait/6tomyri.jpg
Image téléchargée : ../data/paint_portrait/7dante.jpg
Image téléchargée : ../data/paint_portrait/8boccacc.jpg
Image téléchargée : ../data/paint_portrait/9petrarc.jpg
Image téléchargée : ../data/paint_portrait/08portra.jpg
Image téléchargée : ../data/paint_portrait/lucrezia.jpg
Image téléchargée : ../data/paint_portrait/port_lad.jpg
Image téléchargée : ../data/paint_portrait/port_wom.jpg
Image téléchargée : ../data/paint_portrait/portband.jpg
L'image existe déjà : ../data/paint_portrait/youngman.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/fem_port.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/sofonisb.jpg
Image téléchargée : ../data/paint_portrait/campipai.jpg
Image téléchargée : ../data/paint_portrait/chess.jpg
Image téléchargée : ../data/paint_portrait/minerva.jpg
Image téléchargée : ../data/paint_portrait/port_nun.jpg
Image téléchargée : ../data/paint_portrait/profport.jpg
Image téléchargée : ../data/paint_portrait/s_portra.jpg
Image téléchargée : ../data/paint_portrait/self_por.jpg
Image téléchargée : ../data/paint_portrait/selfease.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/selfspin.jpg
Image téléchargée : ../data/paint_portrait/copperco.jpg
Image téléchargée : ../data/paint_portrait/henry8.jpg
Image téléchargée : ../data/paint_portrait/condotti.jpg
Image téléchargée : ../data/paint_portrait/man_port.jpg
Image téléchargée : ../data/paint_portrait/man_porx.jpg
Image téléchargée : ../data/paint_portrait/manportr.jpg
Image téléchargée : ../data/paint_portrait/port_man.jpg
Image téléchargée : ../data/paint_portrait/portra_m.jpg
Image téléchargée : ../data/paint_portrait/portrai.jpg
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/trivulzi.jpg
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrai1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrai2.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/desaix.jpg
Image téléchargée : ../data/paint_portrait/napoleon.jpg
Image téléchargée : ../data/paint_portrait/2portrai.jpg
Image téléchargée : ../data/paint_portrait/pallavic.jpg
Image téléchargée : ../data/paint_portrait/1family.jpg
Image téléchargée : ../data/paint_portrait/1family1.jpg
Image téléchargée : ../data/paint_portrait/2busts1.jpg
Image téléchargée : ../data/paint_portrait/2busts2.jpg
Image téléchargée : ../data/paint_portrait/2busts3.jpg
Image téléchargée : ../data/paint_portrait/2busts4.jpg
Image téléchargée : ../data/paint_portrait/2busts5.jpg
Image téléchargée : ../data/paint_portrait/2busts6.jpg
Image téléchargée : ../data/paint_portrait/4waiter.jpg
Image téléchargée : ../data/paint_portrait/5librari.jpg
Image téléchargée : ../data/paint_portrait/6jurist.jpg
Image téléchargée : ../data/paint_portrait/6jurist1.jpg
Image téléchargée : ../data/paint_portrait/7cook.jpg
Image téléchargée : ../data/paint_portrait/7cook1.jpg
Image téléchargée : ../data/paint_portrait/8garden.jpg
Image téléchargée : ../data/paint_portrait/8garden1.jpg
Image téléchargée : ../data/paint_portrait/peasant.jpg
L'image existe déjà : ../data/paint_portrait/port_wom.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/admiral.jpg
L'image existe déjà : ../data/paint_portrait/portgent.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/heroic.jpg
Image téléchargée : ../data/paint_portrait/raimondi.jpg
Image téléchargée : ../data/paint_portrait/callamar.jpg
L'image existe déjà : ../data/paint_portrait/port_wom.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/embroide.jpg
Image téléchargée : ../data/paint_portrait/m_crozat.jpg
Image téléchargée : ../data/paint_portrait/rameau.jpg
Image téléchargée : ../data/paint_portrait/tessin.jpg
Image téléchargée : ../data/paint_portrait/villiers.jpg
Image téléchargée : ../data/paint_portrait/womancat.jpg
Image téléchargée : ../data/paint_portrait/bernini.jpg
Image téléchargée : ../data/paint_portrait/l_medici.jpg
L'image existe déjà : ../data/paint_portrait/portlady.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/p_lutma.jpg
Image téléchargée : ../data/paint_portrait/port_old.jpg
L'image existe déjà : ../data/paint_portrait/port_wom.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/porthass.jpg
L'image existe déjà : ../data/paint_portrait/portlady.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portlady.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/port_man.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/portwale.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/balassi7.jpg
Image téléchargée : ../data/paint_portrait/balassi8.jpg
Image téléchargée : ../data/paint_portrait/borso.jpg
L'image existe déjà : ../data/paint_portrait/manportr.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrai.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/family.jpg
Image téléchargée : ../data/paint_portrait/ghedini.jpg
L'image existe déjà : ../data/paint_portrait/portlady.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/1young.jpg
Image téléchargée : ../data/paint_portrait/21ludwig.jpg
Image téléchargée : ../data/paint_portrait/2christo.jpg
Image téléchargée : ../data/paint_portrait/3philip.jpg
Image téléchargée : ../data/paint_portrait/4keller.jpg
Image téléchargée : ../data/paint_portrait/z_michel.jpg
Image téléchargée : ../data/paint_portrait/z_selfpo.jpg
Image téléchargée : ../data/paint_portrait/buttler.jpg
Image téléchargée : ../data/paint_portrait/emperor.jpg
Image téléchargée : ../data/paint_portrait/eotvos_j.jpg
Image téléchargée : ../data/paint_portrait/liszt_f.jpg
L'image existe déjà : ../data/paint_portrait/szecheny.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/man_port.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/manpor.jpg
Image téléchargée : ../data/paint_portrait/pacioli.jpg
Image téléchargée : ../data/paint_portrait/frascati.jpg
Image téléchargée : ../data/paint_portrait/venetian.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/francesc.jpg
Image téléchargée : ../data/paint_portrait/ippolito.jpg
Image téléchargée : ../data/paint_portrait/port_gen.jpg
L'image existe déjà : ../data/paint_portrait/port_wom.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portlady.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/selfporx.jpg
Image téléchargée : ../data/paint_portrait/spaniels.jpg
Image téléchargée : ../data/paint_portrait/portbear.jpg
L'image existe déjà : ../data/paint_portrait/portgent.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/portwoma.jpg
Image téléchargée : ../data/paint_portrait/savonaro.jpg
Image téléchargée : ../data/paint_portrait/barbarig.jpg
Image téléchargée : ../data/paint_portrait/man_cap.jpg
Image téléchargée : ../data/paint_portrait/07cardin.jpg
Image téléchargée : ../data/paint_portrait/doge_mem.jpg
Image téléchargée : ../data/paint_portrait/little_g.jpg
Image téléchargée : ../data/paint_portrait/old_man.jpg
Image téléchargée : ../data/paint_portrait/p_aspett.jpg
Image téléchargée : ../data/paint_portrait/p_widow.jpg
Image téléchargée : ../data/paint_portrait/gloves.jpg
L'image existe déjà : ../data/paint_portrait/old_man.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/countess.jpg
Image téléchargée : ../data/paint_portrait/crowle.jpg
Image téléchargée : ../data/paint_portrait/giacinta.jpg
Image téléchargée : ../data/paint_portrait/monino.jpg
Image téléchargée : ../data/paint_portrait/pageturn.jpg
L'image existe déjà : ../data/paint_portrait/portrai1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrai2.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/roberts.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/01pink.jpg
Image téléchargée : ../data/paint_portrait/02selfpo.jpg
Image téléchargée : ../data/paint_portrait/03renoir.jpg
Image téléchargée : ../data/paint_portrait/05family.jpg
Image téléchargée : ../data/paint_portrait/09auriol.jpg
Image téléchargée : ../data/paint_portrait/10studio.jpg
Image téléchargée : ../data/paint_portrait/10studiox.jpg
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/children.jpg
Image téléchargée : ../data/paint_portrait/husband.jpg
Image téléchargée : ../data/paint_portrait/anneaust.jpg
Image téléchargée : ../data/paint_portrait/montpens.jpg
Image téléchargée : ../data/paint_portrait/birds.jpg
Image téléchargée : ../data/paint_portrait/drinker.jpg
Image téléchargée : ../data/paint_portrait/ballplay.jpg
Image téléchargée : ../data/paint_portrait/portr_man.jpg
L'image existe déjà : ../data/paint_portrait/children.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/george4.jpg
Image téléchargée : ../data/paint_portrait/nolleken.jpg
Image téléchargée : ../data/paint_portrait/pigot.jpg
Image téléchargée : ../data/paint_portrait/port_boy.jpg
Image téléchargée : ../data/paint_portrait/simeon.jpg
Image téléchargée : ../data/paint_portrait/stirling.jpg
L'image existe déjà : ../data/paint_portrait/family.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/ludwig_x.jpg
Image téléchargée : ../data/paint_portrait/ludwig10.jpg
Image téléchargée : ../data/paint_portrait/ottheinr.jpg
L'image existe déjà : ../data/paint_portrait/port_man.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/porteck1.jpg
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/gentlema.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/leczinsk.jpg
Image téléchargée : ../data/paint_portrait/louis_14.jpg
Image téléchargée : ../data/paint_portrait/prince.jpg
Image téléchargée : ../data/paint_portrait/sisters.jpg
Image téléchargée : ../data/paint_portrait/cornaro.jpg
Image téléchargée : ../data/paint_portrait/doge.jpg
Image téléchargée : ../data/paint_portrait/mehmet2.jpg
Image téléchargée : ../data/paint_portrait/mocenigo.jpg
Image téléchargée : ../data/paint_portrait/069portr.jpg
Image téléchargée : ../data/paint_portrait/129portr.jpg
Image téléchargée : ../data/paint_portrait/130portr.jpg
Image téléchargée : ../data/paint_portrait/131portr.jpg
Image téléchargée : ../data/paint_portrait/132portr.jpg
Image téléchargée : ../data/paint_portrait/158portr.jpg
Image téléchargée : ../data/paint_portrait/159portr.jpg
Image téléchargée : ../data/paint_portrait/162portr.jpg
Image téléchargée : ../data/paint_portrait/165portr.jpg
Image téléchargée : ../data/paint_portrait/166portr.jpg
Image téléchargée : ../data/paint_portrait/214portr.jpg
Image téléchargée : ../data/paint_portrait/old_phil.jpg
Image téléchargée : ../data/paint_portrait/oldphilo.jpg
Image téléchargée : ../data/paint_portrait/philosop.jpg
Image téléchargée : ../data/paint_portrait/procurat.jpg
Image téléchargée : ../data/paint_portrait/psforza.jpg
Image téléchargée : ../data/paint_portrait/psforza1.jpg
Image téléchargée : ../data/paint_portrait/psforza2.jpg
Image téléchargée : ../data/paint_portrait/5queen.jpg
L'image existe déjà : ../data/paint_portrait/family.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/negress.jpg
Image téléchargée : ../data/paint_portrait/ladyanne.jpg
Image téléchargée : ../data/paint_portrait/mary_mag.jpg
Image téléchargée : ../data/paint_portrait/portrose.jpg
Image téléchargée : ../data/paint_portrait/praying.jpg
Image téléchargée : ../data/paint_portrait/reading.jpg
Image téléchargée : ../data/paint_portrait/blackhat.jpg
Image téléchargée : ../data/paint_portrait/elisa.jpg
Image téléchargée : ../data/paint_portrait/elisa1.jpg
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/aretino.jpg
Image téléchargée : ../data/paint_portrait/peretang.jpg
Image téléchargée : ../data/paint_portrait/turning.jpg
L'image existe déjà : ../data/paint_portrait/port_boy.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/selfpor1.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/selfpor2.jpg
Image téléchargée : ../data/paint_portrait/selfpor3.jpg
Image téléchargée : ../data/paint_portrait/urban8.jpg
Image téléchargée : ../data/paint_portrait/montefel.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/port_man.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/jourdain.jpg
Image téléchargée : ../data/paint_portrait/la_loge.jpg
Image téléchargée : ../data/paint_portrait/blackcap.jpg
Image téléchargée : ../data/paint_portrait/exmewe.jpg
Image téléchargée : ../data/paint_portrait/ffytch.jpg
Image téléchargée : ../data/paint_portrait/elizabe1.jpg
Image téléchargée : ../data/paint_portrait/elizabe2.jpg
Image téléchargée : ../data/paint_portrait/pendant1.jpg
Image téléchargée : ../data/paint_portrait/pendant2.jpg
Image téléchargée : ../data/paint_portrait/marieant.jpg
L'image existe déjà : ../data/paint_portrait/port_boy.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/family.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/port_man.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/breakfas.jpg
Image téléchargée : ../data/paint_portrait/family2.jpg
Image téléchargée : ../data/paint_portrait/musician.jpg
L'image existe déjà : ../data/paint_portrait/selfport.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/fathers.jpg
Image téléchargée : ../data/paint_portrait/pannini.jpg
L'image existe déjà : ../data/paint_portrait/portgent.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/00selfpo.jpg
L'image existe déjà : ../data/paint_portrait/portrai1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrai2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portlady.jpg, téléchargement ignoré.
L'image existe déjà : ../data/paint_portrait/portrait.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/durfort.jpg
L'image existe déjà : ../data/paint_portrait/port_man.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/gypsy_g.jpg
L'image existe déjà : ../data/paint_portrait/port_old.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/ferdinan.jpg
Image téléchargée : ../data/paint_portrait/family1.jpg
L'image existe déjà : ../data/paint_portrait/family2.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/family3.jpg
Image téléchargée : ../data/paint_portrait/1boilly.jpg
Image téléchargée : ../data/paint_portrait/chevrier.jpg
Image téléchargée : ../data/paint_portrait/elleviou.jpg
Image téléchargée : ../data/paint_portrait/gabriell.jpg
Image téléchargée : ../data/paint_portrait/painter.jpg
L'image existe déjà : ../data/paint_portrait/portlady.jpg, téléchargement ignoré.
Image téléchargée : ../data/paint_portrait/aport_ma.jpg
Image téléchargée : ../data/paint_portrait/guild.jpg
Image téléchargée : ../data/paint_portrait/ladpearl.jpg

KeyboardInterrupt:

# IDEA ABORTED
TROP LENT. Je vais juste copier les images télécharger par Idier et prendre seulement les portraits.

In [9]:
import pandas as pd

# Si ton fichier est en CSV :
data_file = "../../data/art_catalog.xlsx"
df = pd.read_excel(data_file)

print(df.columns)  # pour vérifier que "TYPE" et "URL" existent bien

Index(['AUTHOR', 'BORN-DIED', 'TITLE', 'DATE', 'TECHNIQUE', 'LOCATION', 'URL',
       'FORM', 'TYPE', 'SCHOOL', 'TIMEFRAME'],
      dtype='object')

In [10]:
# On garde les lignes où :
#   - FORM contient "painting"
#   - TYPE contient "portrait"
df_portraits = df[
    df["FORM"].str.lower().str.contains("painting", na=False)
    & df["TYPE"].str.lower().str.contains("portrait", na=False)
].copy()

print(f"Nombre total de lignes : {len(df)}")
print(f"Nombre de portraits : {len(df_portraits)}")

Nombre total de lignes : 52867
Nombre de portraits : 4810

In [11]:
def page_url_to_filename(page_url: str) -> str:
    img_url = page_url.replace("/html/", "/detail/").replace(".html", ".jpg")
    return img_url.split("/")[-1]

df_portraits["fname"] = df_portraits["URL"].apply(page_url_to_filename)

In [12]:
import os, shutil

src_dir = "../../data/processed"
dst_dir = "../../data/paint_portrait_only"
os.makedirs(dst_dir, exist_ok=True)

copied = 0
missing = []

for fname in df_portraits["fname"].unique():
    src = os.path.join(src_dir, fname)
    dst = os.path.join(dst_dir, fname)
    if os.path.exists(src):
        shutil.copy2(src, dst)
        copied += 1
    else:
        missing.append(fname)

print(f"✅ {copied} portraits copiés dans {dst_dir}")
print(f"⚠️ {len(missing)} fichiers manquants (peut-être non téléchargés)")

✅ 3592 portraits copiés dans ../../data/paint_portrait_only
⚠️ 0 fichiers manquants (peut-être non téléchargés)